application: meh-antonym
version: 1-adrenochrome
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

# temporary hacks to fix old broken tasks
- url: /_ah/queue/deferred
  #script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  script: antonym/web/success.py
  login: admin    
- url: /_ah/queue/default
  script: antonym/web/success.py
  login: admin    
- url: /safe.*
  script: antonym/web/success.py
  login: admin    

- url: /static
  static_dir: static
    
- url: /_/stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py
  
- url: /cron/.*
  script: antonym/web/cron.py
  login: admin

# - url: /api/artifacts.*
#   script: antonym/web/artifacts.py
- url: /api/config.*
  script: antonym/web/config.py
- url: /api/da.*
  script: antonym/web/da.py
# - url: /api/feeds.*
#   script: antonym/web/feeds.py
# - url: /api/ingest.*
#   script: antonym/web/ingest.py
# - url: /api/mixture.*
#   script: antonym/web/mixtures.py
- url: /api/resources.*
  script: antonym/web/resources.py
# - url: /api/sources.*
#   script: antonym/web/sources.py
- url: /api/twitter.*
  script: antonym/web/tweeter.py
- url: /api/.*
  script: antonym/web/urls.py

# dummy handler for testing
- url: /-/debug/.+
  script: antonym/web/debug.py
 
- url: /(index.html)?
  static_files: static/index.html
  upload: /static/index.html

- url: /-/oauth
  script: antonym/web/ooauth.py

# django
- url: /-/.*
  script: antonym_dj/main.py

admin_console:
  pages:
      - name: Appstats
        url: /_/stats